CREATE TABLE IF NOT EXISTS public.admin_users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'admin' CHECK (role = 'admin'), created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS archived_at timestamptz;
ALTER TABLE public.quotes DROP CONSTRAINT IF EXISTS quotes_status_check;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_status_check CHECK (status IN ('new', 'contacted', 'won', 'lost'));
ALTER TABLE public.quotes DROP CONSTRAINT IF EXISTS quotes_num_pages_check;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_num_pages_check CHECK (num_pages BETWEEN 1 AND 20);
ALTER TABLE public.quotes DROP CONSTRAINT IF EXISTS quotes_num_images_check;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_num_images_check CHECK (num_images BETWEEN 0 AND 100);
ALTER TABLE public.quotes DROP CONSTRAINT IF EXISTS quotes_price_check;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_price_check CHECK (price >= 0 AND price <= 100000);
ALTER TABLE public.quotes DROP CONSTRAINT IF EXISTS quotes_text_lengths_check;
ALTER TABLE public.quotes ADD CONSTRAINT quotes_text_lengths_check CHECK (char_length(website_type) BETWEEN 1 AND 40 AND char_length(languages) <= 200 AND char_length(customer_name) BETWEEN 1 AND 120 AND char_length(customer_email) BETWEEN 3 AND 254 AND char_length(customer_phone) <= 40 AND char_length(notes) <= 2000);
REVOKE INSERT, UPDATE, DELETE ON public.quotes FROM anon, authenticated;
GRANT INSERT (website_type, num_pages, num_images, online_payments, notifications, multilingual, languages, price, customer_name, customer_email, customer_phone, notes) ON public.quotes TO anon, authenticated;
GRANT UPDATE (status, archived_at) ON public.quotes TO authenticated;
DROP POLICY IF EXISTS "anon_insert_quotes" ON public.quotes;
CREATE POLICY "anon_insert_quotes" ON public.quotes FOR INSERT TO anon, authenticated WITH CHECK (status = 'new' AND archived_at IS NULL);
DROP POLICY IF EXISTS "auth_select_quotes" ON public.quotes;
DROP POLICY IF EXISTS "auth_update_quotes" ON public.quotes;
DROP POLICY IF EXISTS "auth_delete_quotes" ON public.quotes;
DROP POLICY IF EXISTS "anon_select_quotes" ON public.quotes;
DROP POLICY IF EXISTS "anon_update_quotes" ON public.quotes;
DROP POLICY IF EXISTS "anon_delete_quotes" ON public.quotes;
CREATE INDEX IF NOT EXISTS quotes_created_at_idx ON public.quotes (created_at DESC);
CREATE INDEX IF NOT EXISTS quotes_archived_at_idx ON public.quotes (archived_at);